use super::*;

const SECTION_TRANSITION_EVENTS: &[(&str, &str)] = &[
    ("ThreadMarkedRead", "default"),
    ("ThreadMarkedUnread", "unread"),
    ("ThreadDismissed", "default"),
];

const CC_ONLY_EVENTS: &[&str] = &[
    "SessionStarted",
    "SessionRecovered",
    "SessionEnded",
    "CodingAgentTextStreamed",
    "CodingAgentToolCalled",
    "CodingAgentToolResult",
    "CodingAgentUserMessageSent",
    "CodingAgentPromptSent",
    "CodingAgentIdled",
    "MissingHardeningDetected",
    "CodingAgentSettingsChanged",
    "UserQuestionAsked",
    "UserQuestionAnswered",
];

fn generate_cross_validation_fixture() -> String {
    let thread_types = [
        ("chat", ThreadType::Chat),
        ("claude_code", ThreadType::CodingAgent),
    ];
    let statuses = [
        ("idle", ThreadStatus::Idle),
        ("running", ThreadStatus::Running),
        ("waiting", ThreadStatus::Waiting),
        (
            "waiting_for_user_answer",
            ThreadStatus::WaitingForUserAnswer,
        ),
        ("failed", ThreadStatus::Failed),
    ];
    let sections = [
        ("default", StoredSection::Default),
        ("unread", StoredSection::Unread),
    ];
    let bools = [false, true];

    let mut cases = Vec::new();

    // resolveActions: 2 types × 3 statuses × 2 sections × 2 pending = 24 cases
    for (tt_str, tt) in &thread_types {
        for (st_str, st) in &statuses {
            for (sec_str, sec) in &sections {
                for &pending in &bools {
                    let actions: Vec<&str> = resolve_actions(*tt, *st, *sec, pending)
                        .iter()
                        .map(|a| match a {
                            Action::Done => "done",
                            Action::Apply => "apply",
                            Action::Discard => "discard",
                        })
                        .collect();
                    cases.push(format!(
                            r#"    {{ "fn": "resolveActions", "args": [{:?}, {:?}, {:?}, {}], "expected": [{}] }}"#,
                            tt_str, st_str, sec_str, pending,
                            actions.iter().map(|a| format!("{:?}", a)).collect::<Vec<_>>().join(", ")
                        ));
                }
            }
        }
    }

    // displaySection: 2 sections × 3 statuses × 2 pinned × 2 activeChildren = 24 cases
    for (sec_str, sec) in &sections {
        for (st_str, st) in &statuses {
            for &pinned in &bools {
                for &active_children in &bools {
                    let result = display_section(*sec, *st, pinned, active_children);
                    let result_str = match result {
                        DisplaySection::Running => "running",
                        DisplaySection::Waiting => "waiting",
                        DisplaySection::Review => "review",
                        DisplaySection::Pinned => "pinned",
                        DisplaySection::History => "history",
                    };
                    cases.push(format!(
                            r#"    {{ "fn": "displaySection", "args": [{:?}, {:?}, {}, {}], "expected": {:?} }}"#,
                            sec_str, st_str, pinned, active_children, result_str
                        ));
                }
            }
        }
    }

    format!("{{\n  \"cases\": [\n{}\n  ]\n}}\n", cases.join(",\n"))
}

fn generate_typescript() -> String {
    let mut out = String::new();

    // Header
    out.push_str("// AUTO-GENERATED by thread_lifecycle.rs — do not edit by hand.\n");
    out.push_str(
        "// Regenerate: cargo test -p cognos-engine generate_typescript_file -- --ignored\n\n",
    );

    // Type aliases
    out.push_str("export type EventChannel = 'chat' | 'claude_code' | 'trigger';\n");
    out.push_str("export const EVENT_CHANNELS: readonly EventChannel[] = ['chat', 'claude_code', 'trigger'] as const;\n");
    out.push_str("export type SessionEndReason = 'completed' | 'user_ended' | 'changes_proposed' | 'changes_applied' | 'auto_ended' | 'shutdown' | 'panic' | 'stale_resume' | 'discarded';\n");
    out.push_str("export const SESSION_END_REASONS: readonly SessionEndReason[] = ['completed', 'user_ended', 'changes_proposed', 'changes_applied', 'auto_ended', 'shutdown', 'panic', 'stale_resume', 'discarded'] as const;\n");
    out.push_str("export type ThreadType = 'chat' | 'claude_code';\n");
    out.push_str("export type StoredSection = 'default' | 'unread';\n");
    out.push_str(
        "export type DisplaySection = 'running' | 'waiting' | 'review' | 'pinned' | 'history';\n",
    );
    out.push_str("export type ThreadStatus = 'idle' | 'running' | 'waiting' | 'waiting_for_user_answer' | 'failed';\n");
    out.push_str("export type EventClass = 'metadata' | 'start' | 'activity' | 'terminal' | 'action_required';\n");
    out.push_str("export type Action = 'done' | 'apply' | 'discard';\n");
    out.push_str("export type MessageLabel = 'Requesting' | 'Working' | 'Waiting' | 'Canceled' | 'Aborted';\n\n");

    // LEGAL_SECTIONS
    out.push_str(
        "export const LEGAL_SECTIONS: Readonly<Record<ThreadType, readonly StoredSection[]>> = {\n",
    );
    out.push_str("  chat: ['default', 'unread'],\n");
    out.push_str("  claude_code: ['default', 'unread'],\n");
    out.push_str("} as const;\n\n");

    // EVENT_CLASSIFICATION
    out.push_str("export const EVENT_CLASSIFICATION: Readonly<Record<string, EventClass>> = {\n");
    for event_type in all_persisted_event_types() {
        if let Some(class) = classify_event(event_type) {
            let class_str = match class {
                EventClass::Metadata => "metadata",
                EventClass::Start => "start",
                EventClass::Activity => "activity",
                EventClass::Terminal => "terminal",
                EventClass::ActionRequired => "action_required",
            };
            out.push_str(&format!("  {}: '{}',\n", event_type, class_str));
        }
    }
    out.push_str("} as const;\n\n");

    // CC_ONLY_EVENTS
    out.push_str("export const CC_ONLY_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in CC_ONLY_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n\n");

    // LAST_ACTIVITY_EVENTS
    out.push_str("export const LAST_ACTIVITY_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in LAST_ACTIVITY_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n\n");

    // isSectionLegal
    out.push_str("export function isSectionLegal(threadType: ThreadType, section: StoredSection): boolean {\n");
    out.push_str("  return (LEGAL_SECTIONS[threadType] as readonly string[]).includes(section);\n");
    out.push_str("}\n\n");

    // displaySection
    out.push_str("export function displaySection(\n");
    out.push_str("  stored: StoredSection,\n");
    out.push_str("  status: ThreadStatus,\n");
    out.push_str("  isPinned: boolean,\n");
    out.push_str("  hasActiveChildren: boolean,\n");
    out.push_str("): DisplaySection {\n");
    out.push_str("  if (status === 'running') return 'running';\n");
    out.push_str("  if (status === 'waiting_for_user_answer') return 'review';\n");
    out.push_str("  if (hasActiveChildren) return 'waiting';\n");
    out.push_str("  if (stored === 'unread') return 'review';\n");
    out.push_str("  return isPinned ? 'pinned' : 'history';\n");
    out.push_str("}\n\n");

    // isCcOnlyEvent
    out.push_str("export function isCcOnlyEvent(eventType: string): boolean {\n");
    out.push_str("  return CC_ONLY_EVENTS.has(eventType);\n");
    out.push_str("}\n");

    // resolveActions
    out.push_str("\nexport function resolveActions(\n");
    out.push_str("  threadType: ThreadType,\n");
    out.push_str("  status: ThreadStatus,\n");
    out.push_str("  storedSection: StoredSection,\n");
    out.push_str("  hasPendingChanges: boolean,\n");
    out.push_str("): Action[] {\n");
    out.push_str("  if (storedSection !== 'unread') return [];\n");
    out.push_str("  if (status === 'running') return [];\n");
    out.push_str("  if (status === 'waiting_for_user_answer') return ['done'];\n");
    out.push_str("  if (threadType === 'chat') return ['done'];\n");
    out.push_str("  return hasPendingChanges ? ['discard', 'apply'] : ['done'];\n");
    out.push_str("}\n");

    // Status transition types
    out.push_str("\nexport type StatusRule =\n");
    out.push_str("  | { kind: 'set'; status: ThreadStatus }\n");
    out.push_str(
        "  | { kind: 'conditional_cc'; withChanges: ThreadStatus; withoutChanges: ThreadStatus }\n",
    );
    out.push_str("  | { kind: 'no_change' };\n\n");

    out.push_str("export type CcFlagRule =\n");
    out.push_str("  | { kind: 'clear_all' }\n");
    out.push_str("  | { kind: 'set_changes' }\n");
    out.push_str("  | { kind: 'set_applying' }\n");
    out.push_str("  | { kind: 'clear_applying' }\n");
    out.push_str("  | { kind: 'from_payload' }\n");
    out.push_str("  | null;\n\n");

    out.push_str("export type StatusTransition = {\n");
    out.push_str("  status: StatusRule;\n");
    out.push_str("  ccFlags: CcFlagRule;\n");
    out.push_str("};\n\n");

    out.push_str(
        "export const STATUS_TRANSITIONS: Readonly<Record<string, StatusTransition>> = {\n",
    );
    for (event, transition) in status_transitions() {
        let status_str = match &transition.status {
            StatusRule::Set(s) => {
                format!("{{ kind: 'set', status: '{}' }}", s.as_str())
            }
            StatusRule::ConditionalCc(with, without) => {
                format!(
                    "{{ kind: 'conditional_cc', withChanges: '{}', withoutChanges: '{}' }}",
                    with.as_str(),
                    without.as_str()
                )
            }
            StatusRule::NoChange => "{ kind: 'no_change' }".to_string(),
        };
        let cc_str = match &transition.cc_flags {
            CcFlagRule::ClearAll => "{ kind: 'clear_all' }",
            CcFlagRule::SetChanges => "{ kind: 'set_changes' }",
            CcFlagRule::SetApplying => "{ kind: 'set_applying' }",
            CcFlagRule::ClearApplying => "{ kind: 'clear_applying' }",
            CcFlagRule::FromPayload => "{ kind: 'from_payload' }",
            CcFlagRule::None => "null",
        };
        out.push_str(&format!(
            "  {}: {{ status: {}, ccFlags: {} }},\n",
            event, status_str, cc_str
        ));
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const SECTION_TRANSITIONS: Readonly<Record<string, StoredSection>> = {\n");
    for (event, section) in SECTION_TRANSITION_EVENTS {
        out.push_str(&format!("  {}: '{}',\n", event, section));
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const MESSAGE_COUNT_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in MESSAGE_COUNT_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n");

    out
}

// 1. every_persisted_event_is_classified
#[test]
fn every_persisted_event_is_classified() {
    for event_type in all_persisted_event_types() {
        assert!(
            classify_event(event_type).is_some(),
            "Persisted event '{}' is not classified",
            event_type
        );
    }
}

// 2. metadata_events_are_correct
#[test]
fn metadata_events_are_correct() {
    let metadata_events = [
        "ThreadTitleGenerated",
        "ThreadTitleRenamed",
        "ThreadPinned",
        "ThreadUnpinned",
        "ThreadMarkedRead",
        "ThreadMarkedUnread",
    ];
    for event_type in &metadata_events {
        assert_eq!(
            classify_event(event_type),
            Some(EventClass::Metadata),
            "'{}' should be Metadata",
            event_type
        );
    }
}

// 3. cc_events_never_classified_as_start
#[test]
fn cc_events_never_classified_as_start() {
    let cc_specific = [
        "CodingAgentTextStreamed",
        "CodingAgentToolCalled",
        "CodingAgentToolResult",
        "CodingAgentPromptSent",
        "CodingAgentIdled",
    ];
    for event_type in &cc_specific {
        let class = classify_event(event_type).unwrap();
        assert_ne!(
            class,
            EventClass::Start,
            "CC-specific event '{}' should not be Start",
            event_type
        );
    }
}

// 4. both_thread_types_share_same_legal_sections
#[test]
fn both_thread_types_share_same_legal_sections() {
    assert!(is_section_legal(ThreadType::Chat, StoredSection::Default));
    assert!(is_section_legal(ThreadType::Chat, StoredSection::Unread));
    assert!(is_section_legal(
        ThreadType::CodingAgent,
        StoredSection::Default
    ));
    assert!(is_section_legal(
        ThreadType::CodingAgent,
        StoredSection::Unread
    ));
}

// 5. response_generated_marks_chat_unread
#[test]
fn response_generated_marks_chat_unread() {
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );
}

// 6. response_generated_does_not_mark_cc_unread
#[test]
fn response_generated_does_not_mark_cc_unread() {
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
    assert!(result.side_effects.is_empty());
}

// 7. claude_code_idled_marks_cc_unread
#[test]
fn claude_code_idled_marks_cc_unread() {
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );
}

// 8. claude_code_idled_rejected_for_chat
#[test]
fn claude_code_idled_rejected_for_chat() {
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    );
    assert!(result.is_err());
}

// 9. change_applied_stays_unread — thread stays in REVIEW so Done button appears
#[test]
fn change_applied_stays_unread() {
    let result = resolve_transition(
        "ChangeApplied",
        ThreadType::CodingAgent,
        StoredSection::Unread,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section, None,
        "ChangeApplied must NOT change section — Done button needs to appear"
    );
    assert!(result.side_effects.is_empty());
}

// 10. change_applied_no_op_if_not_unread
#[test]
fn change_applied_no_op_if_not_unread() {
    let result = resolve_transition(
        "ChangeApplied",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
    assert!(result.side_effects.is_empty());
}

// 11. thread_marked_unread_works_for_both_types
#[test]
fn thread_marked_unread_works_for_both_types() {
    let chat = resolve_transition(
        "ThreadMarkedUnread",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(StoredSection::Unread));

    let cc = resolve_transition(
        "ThreadMarkedUnread",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(StoredSection::Unread));
}

// 12. thread_dismissed_clears_unread_both_types
#[test]
fn thread_dismissed_clears_unread_both_types() {
    let chat = resolve_transition(
        "ThreadDismissed",
        ThreadType::Chat,
        StoredSection::Unread,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(StoredSection::Default));

    let cc = resolve_transition(
        "ThreadDismissed",
        ThreadType::CodingAgent,
        StoredSection::Unread,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(StoredSection::Default));
}

// 13. thread_dismissed_is_terminal
#[test]
fn thread_dismissed_is_terminal() {
    assert_eq!(
        classify_event("ThreadDismissed"),
        Some(EventClass::Terminal)
    );
}

// 14. chat_sub_threads_never_go_to_unread
#[test]
fn chat_sub_threads_never_go_to_unread() {
    // ResponseGenerated for sub-thread chat → stays default
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::Chat,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
    assert!(result.side_effects.is_empty());

    // ThreadMarkedUnread for sub-thread chat → stays default
    let result = resolve_transition(
        "ThreadMarkedUnread",
        ThreadType::Chat,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
    assert!(result.side_effects.is_empty());
}

// 14b. response_aborted_marks_both_thread_types_unread
#[test]
fn response_aborted_marks_both_thread_types_unread() {
    // Chat thread: ResponseAborted → unread
    let chat = resolve_transition(
        "ResponseAborted",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(StoredSection::Unread));
    assert_eq!(chat.side_effects, vec![SideEffect::EmitThreadMarkedUnread]);

    // CC thread: ResponseAborted → unread (aborted CC needs user attention in REVIEW)
    let cc = resolve_transition(
        "ResponseAborted",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(StoredSection::Unread));
    assert_eq!(cc.side_effects, vec![SideEffect::EmitThreadMarkedUnread]);
}

// 14c. response_aborted_chat_sub_thread_stays_default
#[test]
fn response_aborted_chat_sub_thread_stays_default() {
    let result = resolve_transition(
        "ResponseAborted",
        ThreadType::Chat,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
    assert!(result.side_effects.is_empty());
}

// 14d. cc_sub_threads_always_go_to_unread
#[test]
fn cc_sub_threads_always_go_to_unread() {
    // CodingAgentIdled for sub-thread CC → unread (CC always needs user action)
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::CodingAgent,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );

    // ResponseAborted for sub-thread CC → unread
    let result = resolve_transition(
        "ResponseAborted",
        ThreadType::CodingAgent,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );

    // ChangeProposed for sub-thread CC → unread
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        StoredSection::Default,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );
}

// 15. no_transition_produces_illegal_section
#[test]
fn no_transition_produces_illegal_section() {
    let thread_types = [ThreadType::Chat, ThreadType::CodingAgent];
    let sections = [StoredSection::Default, StoredSection::Unread];

    for event_type in all_persisted_event_types() {
        for &thread_type in &thread_types {
            for &section in &sections {
                for is_top in [true, false] {
                    if let Ok(result) = resolve_transition(event_type, thread_type, section, is_top)
                    {
                        if let Some(new_section) = result.new_section {
                            assert!(
                                is_section_legal(thread_type, new_section),
                                "Transition '{}' for {:?} (top={}) produced illegal section {:?}",
                                event_type,
                                thread_type,
                                is_top,
                                new_section
                            );
                        }
                    }
                }
            }
        }
    }
}

// 16. running_status_maps_to_running
#[test]
fn running_status_maps_to_running() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Running, false, false),
        DisplaySection::Running
    );
}

// 17. unread_maps_to_review
#[test]
fn unread_maps_to_review() {
    assert_eq!(
        display_section(StoredSection::Unread, ThreadStatus::Idle, false, false),
        DisplaySection::Review
    );
}

// 18. pinned_default_idle_maps_to_pinned
#[test]
fn pinned_default_idle_maps_to_pinned() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Idle, true, false),
        DisplaySection::Pinned
    );
}

// 19. running_overrides_pinned_to_running
#[test]
fn running_overrides_pinned_to_running() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Running, true, false),
        DisplaySection::Running
    );
}

// 20. default_idle_not_pinned_maps_to_history
#[test]
fn default_idle_not_pinned_maps_to_history() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Idle, false, false),
        DisplaySection::History
    );
}

// 21. active_children_idle_maps_to_waiting
#[test]
fn active_children_idle_maps_to_waiting() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Idle, false, true),
        DisplaySection::Waiting
    );
}

// 22. active_children_overrides_pinned_to_waiting
#[test]
fn active_children_overrides_pinned_to_waiting() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Idle, true, true),
        DisplaySection::Waiting
    );
}

// 22a. running_with_active_children_stays_running
#[test]
fn running_with_active_children_stays_running() {
    assert_eq!(
        display_section(StoredSection::Default, ThreadStatus::Running, false, true),
        DisplaySection::Running
    );
}

// 22b (display). unread_with_active_children_maps_to_waiting
#[test]
fn unread_with_active_children_maps_to_waiting() {
    assert_eq!(
        display_section(StoredSection::Unread, ThreadStatus::Idle, false, true),
        DisplaySection::Waiting
    );
}

// ── resolve_actions tests ──

#[test]
fn chat_unread_idle_shows_done() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Idle,
        StoredSection::Unread,
        false,
    );
    assert_eq!(actions, vec![Action::Done]);
}

#[test]
fn chat_default_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Idle,
        StoredSection::Default,
        false,
    );
    assert!(actions.is_empty());
}

#[test]
fn chat_running_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Running,
        StoredSection::Unread,
        false,
    );
    assert!(actions.is_empty());
}

#[test]
fn cc_unread_with_changes_shows_apply_discard() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        StoredSection::Unread,
        true,
    );
    assert_eq!(actions, vec![Action::Discard, Action::Apply]);
}

#[test]
fn cc_unread_no_changes_shows_done() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        StoredSection::Unread,
        false,
    );
    assert_eq!(actions, vec![Action::Done]);
}

#[test]
fn external_repo_cc_no_pending_change_shows_done() {
    // External repo threads: cc_has_changes=true in thread_summaries but no
    // pending row in the changes table (runtime skips propose_change).
    // has_pending_changes=false → Done, not Apply/Discard.
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        StoredSection::Unread,
        false,
    );
    assert_eq!(
        actions,
        vec![Action::Done],
        "External repo threads without pending changes must show Done, not Apply/Discard"
    );
}

#[test]
fn cc_default_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Idle,
        StoredSection::Default,
        true,
    );
    assert!(actions.is_empty());
}

// ── ChangeProposed must surface CC threads in REVIEW ──

#[test]
fn change_proposed_marks_cc_unread() {
    // Bug: ChangeProposed was in the no_change bucket, so CC threads with
    // proposed changes went to HISTORY instead of REVIEW when there was no
    // prior CodingAgentIdled (or user had already read the thread).
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section,
        Some(StoredSection::Unread),
        "ChangeProposed must mark CC thread as unread to surface Apply panel"
    );
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread],
        "ChangeProposed must emit ThreadMarkedUnread side effect"
    );
}

#[test]
fn change_proposed_keeps_cc_unread_if_already_unread() {
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        StoredSection::Unread,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
}

#[test]
fn cc_running_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Running,
        StoredSection::Unread,
        true,
    );
    assert!(actions.is_empty());
}

// ── UserQuestionAsked / UserQuestionAnswered tests ──

#[test]
fn user_question_asked_marks_cc_unread() {
    let result = resolve_transition(
        "UserQuestionAsked",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(StoredSection::Unread));
    assert_eq!(
        result.side_effects,
        vec![SideEffect::EmitThreadMarkedUnread]
    );
}

#[test]
fn user_question_asked_rejected_for_chat() {
    let result = resolve_transition(
        "UserQuestionAsked",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    );
    assert!(result.is_err(), "UserQuestionAsked must be CC-only");
}

#[test]
fn user_question_answered_no_section_change() {
    let result = resolve_transition(
        "UserQuestionAnswered",
        ThreadType::CodingAgent,
        StoredSection::Unread,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section, None,
        "answer event keeps thread in REVIEW until next terminal"
    );
    assert!(result.side_effects.is_empty());
}

#[test]
fn user_question_asked_classified_action_required() {
    assert_eq!(
        classify_event("UserQuestionAsked"),
        Some(EventClass::ActionRequired)
    );
}

#[test]
fn user_question_asked_status_transition() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    let t = transitions
        .get("UserQuestionAsked")
        .expect("status transition");
    assert_eq!(
        t.status,
        StatusRule::Set(ThreadStatus::WaitingForUserAnswer)
    );
    assert_eq!(t.cc_flags, CcFlagRule::None);
}

#[test]
fn user_question_answered_status_transition_resumes_running() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    let t = transitions
        .get("UserQuestionAnswered")
        .expect("status transition");
    assert_eq!(t.status, StatusRule::Set(ThreadStatus::Running));
}

#[test]
fn waiting_for_user_answer_routes_to_review() {
    // Both stored sections route to REVIEW so the question card is reachable.
    assert_eq!(
        display_section(
            StoredSection::Default,
            ThreadStatus::WaitingForUserAnswer,
            false,
            false
        ),
        DisplaySection::Review
    );
    assert_eq!(
        display_section(
            StoredSection::Unread,
            ThreadStatus::WaitingForUserAnswer,
            false,
            false
        ),
        DisplaySection::Review
    );
    // Even with active children the question takes precedence — the user must answer.
    assert_eq!(
        display_section(
            StoredSection::Default,
            ThreadStatus::WaitingForUserAnswer,
            false,
            true
        ),
        DisplaySection::Review
    );
}

#[test]
fn waiting_for_user_answer_shows_done_only() {
    // QuestionCard owns answer/free-text, but the user must still be able to
    // abandon the question. Show Done (which auto-cancels the question on the
    // backend); never Apply/Discard since the mid-turn work is incomplete.
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::WaitingForUserAnswer,
        StoredSection::Unread,
        true,
    );
    assert_eq!(
        actions,
        vec![Action::Done],
        "Done must be available so the user can dismiss the thread"
    );

    let no_changes = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::WaitingForUserAnswer,
        StoredSection::Unread,
        false,
    );
    assert_eq!(no_changes, vec![Action::Done]);

    // Default section (already dismissed/read) → no actions.
    let default = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::WaitingForUserAnswer,
        StoredSection::Default,
        true,
    );
    assert!(default.is_empty(), "no actions when not in REVIEW");
}

#[test]
fn user_question_events_are_persisted() {
    assert!(all_persisted_event_types().contains(&"UserQuestionAsked"));
    assert!(all_persisted_event_types().contains(&"UserQuestionAnswered"));
}

// CodingAgentSettingsChanged must be accepted for CC threads (persisted metadata, no section change)
#[test]
fn cc_settings_changed_accepted_for_cc_threads() {
    let result = resolve_transition(
        "CodingAgentSettingsChanged",
        ThreadType::CodingAgent,
        StoredSection::Default,
        true,
    );
    assert!(
        result.is_ok(),
        "CodingAgentSettingsChanged must be accepted for CC threads"
    );
    let result = result.unwrap();
    assert_eq!(
        result.new_section, None,
        "CodingAgentSettingsChanged must not change section"
    );
    assert!(
        result.side_effects.is_empty(),
        "CodingAgentSettingsChanged must have no side effects"
    );
}

#[test]
fn cc_settings_changed_rejected_for_chat_threads() {
    let result = resolve_transition(
        "CodingAgentSettingsChanged",
        ThreadType::Chat,
        StoredSection::Default,
        true,
    );
    assert!(
        result.is_err(),
        "CodingAgentSettingsChanged must be rejected for Chat threads"
    );
}

#[test]
fn cc_settings_changed_is_classified() {
    assert!(
        classify_event("CodingAgentSettingsChanged").is_some(),
        "CodingAgentSettingsChanged must be classified"
    );
}

#[test]
fn cc_settings_changed_is_persisted_event() {
    assert!(
        all_persisted_event_types().contains(&"CodingAgentSettingsChanged"),
        "CodingAgentSettingsChanged must be in all_persisted_event_types()"
    );
}

// 22b. last_activity_events_are_valid_persisted_events
#[test]
fn last_activity_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for event in LAST_ACTIVITY_EVENTS {
        assert!(
            all.contains(event),
            "LAST_ACTIVITY_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// Events that update last_activity in the backend projection (event_bus.rs)
// must be in LAST_ACTIVITY_EVENTS so the frontend drawer timestamp stays in sync.
#[test]
fn required_events_are_in_last_activity() {
    for event in &[
        "ToolCalled",
        "ToolResult",
        "TextStreamed",
        "Thinking",
        "CodingAgentTextStreamed",
        "CodingAgentToolCalled",
        "CodingAgentToolResult",
        "TriggerCompleted",
    ] {
        assert!(
            LAST_ACTIVITY_EVENTS.contains(event),
            "'{}' must be in LAST_ACTIVITY_EVENTS — it updates last_activity in \
                 event_bus.rs but the frontend won't sync without it",
            event
        );
    }
}

#[test]
fn status_transition_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in status_transitions() {
        assert!(
            all.contains(&event),
            "status_transitions contains '{}' which is not a persisted event type",
            event
        );
    }
}

#[test]
fn message_count_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for event in MESSAGE_COUNT_EVENTS {
        assert!(
            all.contains(event),
            "MESSAGE_COUNT_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// 22c. cross_validation_fixture_is_up_to_date
#[test]
fn cross_validation_fixture_is_up_to_date() {
    let generated = generate_cross_validation_fixture();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cognos-app/src/generated/cross-validation-fixture.json");
    if let Ok(existing) = std::fs::read_to_string(&path) {
        assert_eq!(
                existing, generated,
                "Cross-validation fixture is stale. Run: cargo test -p cognos-engine generate_cross_validation_fixture_file -- --ignored"
            );
    } else {
        panic!(
                "Cross-validation fixture does not exist at {}. Run: cargo test -p cognos-engine generate_cross_validation_fixture_file -- --ignored",
                path.display()
            );
    }
}

// 23. generated_typescript_is_up_to_date
#[test]
fn generated_typescript_is_up_to_date() {
    let generated = generate_typescript();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cognos-app/src/generated/thread-lifecycle.ts");
    if let Ok(existing) = std::fs::read_to_string(&path) {
        assert_eq!(
                existing, generated,
                "Generated TypeScript is stale. Run: cargo test -p cognos-engine generate_typescript_file -- --ignored"
            );
    } else {
        panic!(
                "Generated file does not exist at {}. Run: cargo test -p cognos-engine generate_typescript_file -- --ignored",
                path.display()
            );
    }
}

// 24. generate_typescript_file (run explicitly to regenerate)
#[test]
#[ignore]
fn generate_typescript_file() {
    let generated = generate_typescript();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cognos-app/src/generated/thread-lifecycle.ts");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, &generated).unwrap();
    crate::log!("[ContractTest] Generated: {}", path.display());
}

// 24b. generate_cross_validation_fixture_file (run explicitly to regenerate)
#[test]
#[ignore]
fn generate_cross_validation_fixture_file() {
    let generated = generate_cross_validation_fixture();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cognos-app/src/generated/cross-validation-fixture.json");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, &generated).unwrap();
    crate::log!("[ContractTest] Generated: {}", path.display());
}

// 25. start_events_set_status_running
#[test]
fn start_events_with_transitions_set_running() {
    // Start classification is about exchange grouping (UI), not status.
    // Some Start events (MissingHardeningDetected, MergeConflictDetected) don't
    // set status=running in event_bus.rs. This test only checks that Start events
    // that DO have a status transition always set Running (never idle/waiting).
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for event_type in all_persisted_event_types() {
        if classify_event(event_type) == Some(EventClass::Start) {
            if let Some(t) = transitions.get(event_type) {
                if let StatusRule::Set(s) = &t.status {
                    assert_eq!(
                        *s,
                        ThreadStatus::Running,
                        "Start event '{}' with Set status should set Running, not {:?}",
                        event_type,
                        s
                    );
                }
            }
        }
    }
}

// 26. terminal_events_never_set_running
#[test]
fn terminal_events_never_set_running() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for event_type in all_persisted_event_types() {
        if classify_event(event_type) == Some(EventClass::Terminal) {
            if let Some(t) = transitions.get(event_type) {
                match &t.status {
                    StatusRule::Set(s) => assert_ne!(
                        *s,
                        ThreadStatus::Running,
                        "Terminal event '{}' should not set Running",
                        event_type
                    ),
                    StatusRule::ConditionalCc(w, wo) => {
                        assert_ne!(
                            *w,
                            ThreadStatus::Running,
                            "Terminal '{}' withChanges should not be Running",
                            event_type
                        );
                        assert_ne!(
                            *wo,
                            ThreadStatus::Running,
                            "Terminal '{}' withoutChanges should not be Running",
                            event_type
                        );
                    }
                    StatusRule::NoChange => {}
                }
            }
        }
    }
}

// 27. section_transition_events_are_valid_persisted_events
#[test]
fn section_transition_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in SECTION_TRANSITION_EVENTS {
        assert!(
            all.contains(event),
            "SECTION_TRANSITION_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// ── Phase 0: Pre-refactor safety net ──

/// Cross-validate: events with status_transitions Setting → Running must be
/// classified as Start (or at least not Terminal). Events Setting → Idle/Waiting
/// must NOT be classified as Start.
#[test]
fn status_transition_classification_consistency() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for (event, transition) in &transitions {
        let class = classify_event(event);
        match &transition.status {
            StatusRule::Set(ThreadStatus::Running) => {
                // Running-setters should be Start or Activity, never Terminal
                if let Some(c) = class {
                    assert_ne!(
                        c,
                        EventClass::Terminal,
                        "Event '{}' sets Running but is classified as Terminal",
                        event
                    );
                }
            }
            StatusRule::Set(ThreadStatus::Idle)
            | StatusRule::Set(ThreadStatus::Waiting)
            | StatusRule::Set(ThreadStatus::Failed) => {
                // Idle/Waiting/Failed-setters should NOT be Start
                if let Some(c) = class {
                    assert_ne!(
                        c,
                        EventClass::Start,
                        "Event '{}' sets non-running terminal status but is classified as Start",
                        event
                    );
                }
            }
            _ => {} // ConditionalCc and NoChange are fine in any class
        }
    }
}

/// Cross-validate: CcFlagRule != None should only appear on CC-relevant events
/// (Change*, ClaudeCode*, MergeConflict*, ThreadDismissed). This catches accidental
/// cc_has_changes/cc_applying mutations on chat-only events.
#[test]
fn cc_flag_rules_only_on_cc_relevant_events() {
    let cc_relevant_prefixes = ["Change", "CodingAgent", "MergeConflict", "ThreadDismissed"];
    for (event, transition) in status_transitions() {
        if transition.cc_flags != CcFlagRule::None {
            let is_cc_relevant = cc_relevant_prefixes
                .iter()
                .any(|prefix| event.starts_with(prefix));
            assert!(
                is_cc_relevant,
                "Event '{}' has CcFlagRule {:?} but doesn't match any CC-relevant prefix {:?}",
                event, transition.cc_flags, cc_relevant_prefixes
            );
        }
    }
}

/// Cross-validate: MESSAGE_COUNT_EVENTS should all be Start events —
/// only user-initiated "start of exchange" events increment the count.
#[test]
fn message_count_events_are_start_events() {
    for event in MESSAGE_COUNT_EVENTS {
        let class = classify_event(event);
        assert_eq!(
                class,
                Some(EventClass::Start),
                "MESSAGE_COUNT_EVENT '{}' should be classified as Start (it starts a new exchange), got {:?}",
                event, class
            );
    }
}

/// Cross-validate: every event that has a StatusTransition must be a persisted
/// event type. Transient events should never appear in status_transitions().
#[test]
fn status_transitions_only_contain_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in status_transitions() {
        assert!(
            all.contains(&event),
            "status_transitions() contains '{}' which is not in all_persisted_event_types(). \
                 Transient events must not have status transitions.",
            event
        );
    }
}

/// Cross-validate: Start events that set status=Running should also appear in
/// LAST_ACTIVITY_EVENTS (they start a new exchange, so they're activity).
/// Activity-classified events (like CodingAgentPromptSent) may set Running
/// without updating last_activity — they only update last_revived_at.
#[test]
fn start_running_setters_are_in_last_activity_events() {
    for (event, transition) in status_transitions() {
        if let StatusRule::Set(ThreadStatus::Running) = transition.status {
            if classify_event(event) == Some(EventClass::Start) {
                assert!(
                    LAST_ACTIVITY_EVENTS.contains(&event),
                    "Start event '{}' sets status=Running but is NOT in LAST_ACTIVITY_EVENTS. \
                         Start events begin new exchanges and should update last_activity.",
                    event
                );
            }
        }
    }
}
