use super::*;

const SECTION_TRANSITION_EVENTS: &[(&str, &str)] = &[
    ("ThreadArchived", "archived"),
];

const CC_ONLY_EVENTS: &[&str] = &[
    "SessionStarted",
    "SessionRecovered",
    "SessionEnded",
    "CodingAgentTextStreamed",
    "CodingAgentToolCalled",
    "CodingAgentToolResult",
    "CodingAgentUserMessageSent",
    "CodingAgentPromptSent",
    "CodingAgentIdled",
    "ContinueSignal",
    "MissingHardeningDetected",
    "CodingAgentSettingsChanged",
    "UserQuestionAsked",
    "UserQuestionAnswered",
];

fn generate_cross_validation_fixture() -> String {
    let thread_types = [
        ("chat", ThreadType::Chat),
        ("claude_code", ThreadType::CodingAgent),
    ];
    let statuses = [
        ("idle", ThreadStatus::Idle),
        ("running", ThreadStatus::Running),
        ("waiting", ThreadStatus::Waiting),
        (
            "waiting_for_user_answer",
            ThreadStatus::WaitingForUserAnswer,
        ),
        ("failed", ThreadStatus::Failed),
    ];
    let sections = [
        ("archived", ArchiveState::Archived),
        ("inbox", ArchiveState::Inbox),
    ];
    let bools = [false, true];

    let mut cases = Vec::new();

    // resolveActions: 2 types × 3 statuses × 2 sections × 2 pending = 24 cases
    for (tt_str, tt) in &thread_types {
        for (st_str, st) in &statuses {
            for (sec_str, sec) in &sections {
                for &pending in &bools {
                    let actions: Vec<&str> = resolve_actions(*tt, *st, *sec, pending)
                        .iter()
                        .map(|a| match a {
                            Action::Archive => "archive",
                            Action::Apply => "apply",
                            Action::Discard => "discard",
                        })
                        .collect();
                    cases.push(format!(
                            r#"    {{ "fn": "resolveActions", "args": [{:?}, {:?}, {:?}, {}], "expected": [{}] }}"#,
                            tt_str, st_str, sec_str, pending,
                            actions.iter().map(|a| format!("{:?}", a)).collect::<Vec<_>>().join(", ")
                        ));
                }
            }
        }
    }

    // displaySection: 2 sections × 3 statuses × 2 saved × 2 activeChildren × 2 pending = 48 cases
    for (sec_str, sec) in &sections {
        for (st_str, st) in &statuses {
            for &saved in &bools {
                for &active_children in &bools {
                    for &pending in &bools {
                        let result = display_section(*sec, *st, saved, active_children, pending);
                        let result_str = match result {
                            DisplaySection::Active => "active",
                            DisplaySection::Review => "review",
                            DisplaySection::Saved => "saved",
                            DisplaySection::Archive => "archive",
                        };
                        cases.push(format!(
                                r#"    {{ "fn": "displaySection", "args": [{:?}, {:?}, {}, {}, {}], "expected": {:?} }}"#,
                                sec_str, st_str, saved, active_children, pending, result_str
                            ));
                    }
                }
            }
        }
    }

    format!("{{\n  \"cases\": [\n{}\n  ]\n}}\n", cases.join(",\n"))
}

fn generate_typescript() -> String {
    let mut out = String::new();

    // Header
    out.push_str("// AUTO-GENERATED by thread_lifecycle.rs — do not edit by hand.\n");
    out.push_str(
        "// Regenerate: cargo test -p lucidos-engine generate_typescript_file -- --ignored\n\n",
    );

    // Type aliases
    out.push_str("export type EventChannel = 'chat' | 'claude_code' | 'trigger';\n");
    out.push_str("export const EVENT_CHANNELS: readonly EventChannel[] = ['chat', 'claude_code', 'trigger'] as const;\n");
    out.push_str("export type SessionEndReason = 'shutdown' | 'panic' | 'closed' | 'stale_resume' | 'legacy_non_terminal';\n");
    out.push_str("export const SESSION_END_REASONS: readonly SessionEndReason[] = ['shutdown', 'panic', 'closed', 'stale_resume', 'legacy_non_terminal'] as const;\n");
    out.push_str("export type ThreadType = 'chat' | 'claude_code';\n");
    out.push_str("export type ArchiveState = 'archived' | 'inbox';\n");
    out.push_str(
        "export type DisplaySection = 'active' | 'saved' | 'review' | 'archive';\n",
    );
    out.push_str("export type ThreadStatus = 'idle' | 'running' | 'waiting' | 'waiting_for_user_answer' | 'failed';\n");
    out.push_str("export type EventClass = 'metadata' | 'start' | 'activity' | 'terminal' | 'action_required';\n");
    out.push_str("export type Action = 'archive' | 'apply' | 'discard';\n");
    out.push_str("export type MessageLabel = 'Requesting' | 'Working' | 'Waiting' | 'Canceled' | 'Aborted';\n\n");

    // LEGAL_SECTIONS
    out.push_str(
        "export const LEGAL_SECTIONS: Readonly<Record<ThreadType, readonly ArchiveState[]>> = {\n",
    );
    out.push_str("  chat: ['archived', 'inbox'],\n");
    out.push_str("  claude_code: ['archived', 'inbox'],\n");
    out.push_str("} as const;\n\n");

    // EVENT_CLASSIFICATION
    out.push_str("export const EVENT_CLASSIFICATION: Readonly<Record<string, EventClass>> = {\n");
    for event_type in all_persisted_event_types() {
        if let Some(class) = classify_event(event_type) {
            let class_str = match class {
                EventClass::Metadata => "metadata",
                EventClass::Start => "start",
                EventClass::Activity => "activity",
                EventClass::Terminal => "terminal",
                EventClass::ActionRequired => "action_required",
            };
            out.push_str(&format!("  {}: '{}',\n", event_type, class_str));
        }
    }
    out.push_str("} as const;\n\n");

    // CC_ONLY_EVENTS
    out.push_str("export const CC_ONLY_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in CC_ONLY_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n\n");

    // LAST_ACTIVITY_EVENTS
    out.push_str("export const LAST_ACTIVITY_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in LAST_ACTIVITY_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n\n");

    // isSectionLegal
    out.push_str("export function isSectionLegal(threadType: ThreadType, section: ArchiveState): boolean {\n");
    out.push_str("  return (LEGAL_SECTIONS[threadType] as readonly string[]).includes(section);\n");
    out.push_str("}\n\n");

    // displaySection
    out.push_str("export function displaySection(\n");
    out.push_str("  stored: ArchiveState,\n");
    out.push_str("  status: ThreadStatus,\n");
    out.push_str("  isSaved: boolean,\n");
    out.push_str("  hasActiveChildren: boolean,\n");
    out.push_str("  hasPendingChanges: boolean,\n");
    out.push_str("): DisplaySection {\n");
    out.push_str("  if (isSaved) return 'saved';\n");
    out.push_str("  if (status === 'running' || hasActiveChildren) return 'active';\n");
    out.push_str("  if (hasPendingChanges) return 'review';\n");
    out.push_str("  if (stored === 'archived') return 'archive';\n");
    out.push_str("  return 'review';\n");
    out.push_str("}\n\n");

    // isCcOnlyEvent
    out.push_str("export function isCcOnlyEvent(eventType: string): boolean {\n");
    out.push_str("  return CC_ONLY_EVENTS.has(eventType);\n");
    out.push_str("}\n");

    // resolveActions
    out.push_str("\nexport function resolveActions(\n");
    out.push_str("  threadType: ThreadType,\n");
    out.push_str("  status: ThreadStatus,\n");
    out.push_str("  storedSection: ArchiveState,\n");
    out.push_str("  hasPendingChanges: boolean,\n");
    out.push_str("): Action[] {\n");
    out.push_str("  if (status === 'running' || status === 'waiting_for_user_answer') return [];\n");
    out.push_str("  if (hasPendingChanges && threadType === 'claude_code') return ['discard', 'apply'];\n");
    out.push_str("  if (storedSection !== 'inbox') return [];\n");
    out.push_str("  return ['archive'];\n");
    out.push_str("}\n");

    // STATUS_TRANSITIONS / SECTION_TRANSITIONS removed in Phase 5: the
    // frontend now sources thread.meta.status and thread.meta.section
    // exclusively from the per-event ThreadAggregate snapshot, so the
    // generated lookup tables and their supporting types (StatusRule,
    // CcFlagRule, StatusTransition) are no longer consumed.

    out.push_str("export const MESSAGE_COUNT_EVENTS: ReadonlySet<string> = new Set([\n");
    for event in MESSAGE_COUNT_EVENTS {
        out.push_str(&format!("  '{}',\n", event));
    }
    out.push_str("]);\n");

    out
}

// 1. every_persisted_event_is_classified
#[test]
fn every_persisted_event_is_classified() {
    for event_type in all_persisted_event_types() {
        assert!(
            classify_event(event_type).is_some(),
            "Persisted event '{}' is not classified",
            event_type
        );
    }
}

// 2. metadata_events_are_correct
#[test]
fn metadata_events_are_correct() {
    let metadata_events = [
        "ThreadTitleGenerated",
        "ThreadTitleRenamed",
        "ThreadSaved",
        "ThreadUnsaved",
    ];
    for event_type in &metadata_events {
        assert_eq!(
            classify_event(event_type),
            Some(EventClass::Metadata),
            "'{}' should be Metadata",
            event_type
        );
    }
}

// 3. cc_events_never_classified_as_start
#[test]
fn cc_events_never_classified_as_start() {
    let cc_specific = [
        "CodingAgentTextStreamed",
        "CodingAgentToolCalled",
        "CodingAgentToolResult",
        "CodingAgentPromptSent",
        "CodingAgentIdled",
    ];
    for event_type in &cc_specific {
        let class = classify_event(event_type).unwrap();
        assert_ne!(
            class,
            EventClass::Start,
            "CC-specific event '{}' should not be Start",
            event_type
        );
    }
}

// 4. both_thread_types_share_same_legal_sections
#[test]
fn both_thread_types_share_same_legal_sections() {
    assert!(is_section_legal(ThreadType::Chat, ArchiveState::Archived));
    assert!(is_section_legal(ThreadType::Chat, ArchiveState::Inbox));
    assert!(is_section_legal(
        ThreadType::CodingAgent,
        ArchiveState::Archived
    ));
    assert!(is_section_legal(
        ThreadType::CodingAgent,
        ArchiveState::Inbox
    ));
}

// 5. response_generated_surfaces_chat_to_inbox
#[test]
fn response_generated_surfaces_chat_to_inbox() {
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));}

// 6. response_generated_does_not_surface_cc
#[test]
fn response_generated_does_not_surface_cc() {
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
}

// 7. claude_code_idled_surfaces_cc_to_inbox
#[test]
fn claude_code_idled_surfaces_cc_to_inbox() {
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));}

// 8. claude_code_idled_rejected_for_chat
#[test]
fn claude_code_idled_rejected_for_chat() {
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    );
    assert!(result.is_err());
}

// 9. change_applied_keeps_inbox — thread stays in REVIEW so Archive button appears
#[test]
fn change_applied_keeps_inbox() {
    let result = resolve_transition(
        "ChangeApplied",
        ThreadType::CodingAgent,
        ArchiveState::Inbox,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section, None,
        "ChangeApplied must NOT change section — Archive button needs to appear"
    );
}

// 10. change_applied_no_op_if_not_in_inbox
#[test]
fn change_applied_no_op_if_not_in_inbox() {
    let result = resolve_transition(
        "ChangeApplied",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
}

// 12. thread_archived_clears_inbox_both_types
#[test]
fn thread_archived_clears_inbox_both_types() {
    let chat = resolve_transition(
        "ThreadArchived",
        ThreadType::Chat,
        ArchiveState::Inbox,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(ArchiveState::Archived));

    let cc = resolve_transition(
        "ThreadArchived",
        ThreadType::CodingAgent,
        ArchiveState::Inbox,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(ArchiveState::Archived));
}

// 13. thread_archived_is_terminal
#[test]
fn thread_archived_is_terminal() {
    assert_eq!(
        classify_event("ThreadArchived"),
        Some(EventClass::Terminal)
    );
}

// 14. chat_sub_threads_never_go_to_inbox
#[test]
fn chat_sub_threads_never_go_to_inbox() {
    // ResponseGenerated for sub-thread chat → stays archived
    let result = resolve_transition(
        "ResponseGenerated",
        ThreadType::Chat,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
}

// 14b. response_aborted_surfaces_both_thread_types_to_inbox
#[test]
fn response_aborted_surfaces_both_thread_types_to_inbox() {
    // Chat thread: ResponseAborted → inbox
    let chat = resolve_transition(
        "ResponseAborted",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(ArchiveState::Inbox));

    // CC thread: ResponseAborted → inbox (aborted CC needs user attention in REVIEW)
    let cc = resolve_transition(
        "ResponseAborted",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(ArchiveState::Inbox));
}

// 14c. response_aborted_chat_sub_thread_stays_default
#[test]
fn response_aborted_chat_sub_thread_stays_default() {
    let result = resolve_transition(
        "ResponseAborted",
        ThreadType::Chat,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
}

// CC threads also receive a CodingAgentIdled after ResponseCanceled in the
// normal path, but the no-session settle fallback (claude_code.rs) emits
// ResponseCanceled alone — so the inbox transition must hold for both.
#[test]
fn response_canceled_surfaces_both_thread_types_to_inbox() {
    let chat = resolve_transition(
        "ResponseCanceled",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(chat.new_section, Some(ArchiveState::Inbox));

    let cc = resolve_transition(
        "ResponseCanceled",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(cc.new_section, Some(ArchiveState::Inbox));
}

#[test]
fn response_canceled_chat_sub_thread_stays_default() {
    let result = resolve_transition(
        "ResponseCanceled",
        ThreadType::Chat,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, None);
}

// 14d. cc_sub_threads_always_go_to_inbox
#[test]
fn cc_sub_threads_always_go_to_inbox() {
    // CodingAgentIdled for sub-thread CC → inbox (CC always needs user action)
    let result = resolve_transition(
        "CodingAgentIdled",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));    // ResponseAborted for sub-thread CC → inbox
    let result = resolve_transition(
        "ResponseAborted",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));    // ChangeProposed for sub-thread CC → inbox
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        false,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));}

// 15. no_transition_produces_illegal_section
#[test]
fn no_transition_produces_illegal_section() {
    let thread_types = [ThreadType::Chat, ThreadType::CodingAgent];
    let sections = [ArchiveState::Archived, ArchiveState::Inbox];

    for event_type in all_persisted_event_types() {
        for &thread_type in &thread_types {
            for &section in &sections {
                for is_top in [true, false] {
                    if let Ok(result) = resolve_transition(event_type, thread_type, section, is_top)
                    {
                        if let Some(new_section) = result.new_section {
                            assert!(
                                is_section_legal(thread_type, new_section),
                                "Transition '{}' for {:?} (top={}) produced illegal section {:?}",
                                event_type,
                                thread_type,
                                is_top,
                                new_section
                            );
                        }
                    }
                }
            }
        }
    }
}

// 16. running_status_maps_to_running
#[test]
fn running_status_maps_to_running() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Running, false, false, false),
        DisplaySection::Active
    );
}

// 17. inbox_maps_to_review
#[test]
fn inbox_maps_to_review() {
    assert_eq!(
        display_section(ArchiveState::Inbox, ThreadStatus::Idle, false, false, false),
        DisplaySection::Review
    );
}

// 18. saved_default_idle_maps_to_saved
#[test]
fn saved_default_idle_maps_to_saved() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, true, false, false),
        DisplaySection::Saved
    );
}

// 19. saved_overrides_running — under the new routing saved wins everything
#[test]
fn saved_overrides_running_to_saved() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Running, true, false, false),
        DisplaySection::Saved
    );
}

// 20. archived_idle_not_saved_maps_to_archive
#[test]
fn archived_idle_not_saved_maps_to_archive() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, false, false, false),
        DisplaySection::Archive
    );
}

// 21. active_children_idle_maps_to_active — Waiting was folded into Active
#[test]
fn active_children_idle_maps_to_active() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, false, true, false),
        DisplaySection::Active
    );
}

// 22. active_children_saved_still_saved — save overrides delegated work
#[test]
fn active_children_saved_still_saved() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, true, true, false),
        DisplaySection::Saved
    );
}

// 22a. running_with_active_children_stays_active
#[test]
fn running_with_active_children_stays_active() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Running, false, true, false),
        DisplaySection::Active
    );
}

// 22b. inbox_with_active_children_maps_to_active
#[test]
fn inbox_with_active_children_maps_to_active() {
    assert_eq!(
        display_section(ArchiveState::Inbox, ThreadStatus::Idle, false, true, false),
        DisplaySection::Active
    );
}

// 22c. inbox_idle_no_children_maps_to_review
#[test]
fn inbox_idle_no_children_maps_to_review() {
    assert_eq!(
        display_section(ArchiveState::Inbox, ThreadStatus::Idle, false, false, false),
        DisplaySection::Review
    );
}

// 22d. archived_with_pending_changes_routes_to_review — pending changes
//      outrank archive so users can never lose unresolved work behind the
//      archive curtain. Once the user resolves all pending changes, the
//      thread settles into Archive (covered by 20).
#[test]
fn archived_with_pending_changes_routes_to_review() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, false, false, true),
        DisplaySection::Review
    );
}

// 22e. saved_overrides_pending — saving is still the strongest claim;
//      a pending change on a saved thread surfaces via the Saved section's
//      CTA badge, not by overriding routing.
#[test]
fn saved_overrides_pending() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Idle, true, false, true),
        DisplaySection::Saved
    );
}

// 22f. running_overrides_pending — Active wins so live work isn't masked
//      by a pending change row carried in from a previous turn.
#[test]
fn running_overrides_pending() {
    assert_eq!(
        display_section(ArchiveState::Archived, ThreadStatus::Running, false, false, true),
        DisplaySection::Active
    );
}

// ── resolve_actions tests ──

#[test]
fn chat_inbox_idle_shows_archive() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Idle,
        ArchiveState::Inbox,
        false,
    );
    assert_eq!(actions, vec![Action::Archive]);
}

#[test]
fn chat_default_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Idle,
        ArchiveState::Archived,
        false,
    );
    assert!(actions.is_empty());
}

#[test]
fn chat_running_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::Chat,
        ThreadStatus::Running,
        ArchiveState::Inbox,
        false,
    );
    assert!(actions.is_empty());
}

#[test]
fn cc_inbox_with_changes_shows_apply_discard() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        ArchiveState::Inbox,
        true,
    );
    assert_eq!(actions, vec![Action::Discard, Action::Apply]);
}

#[test]
fn cc_inbox_no_changes_shows_archive() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        ArchiveState::Inbox,
        false,
    );
    assert_eq!(actions, vec![Action::Archive]);
}

#[test]
fn external_repo_cc_no_pending_change_shows_archive() {
    // External repo threads: cc_has_changes=true in thread_summaries but no
    // pending row in the changes table (runtime skips propose_change).
    // has_pending_changes=false → Archive, not Apply/Discard.
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        ArchiveState::Inbox,
        false,
    );
    assert_eq!(
        actions,
        vec![Action::Archive],
        "External repo threads without pending changes must show Done, not Apply/Discard"
    );
}

#[test]
fn cc_archived_no_changes_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Idle,
        ArchiveState::Archived,
        false,
    );
    assert!(actions.is_empty());
}

#[test]
fn cc_archived_with_pending_changes_shows_apply_discard() {
    // display_section surfaces archived+pending threads in Review specifically
    // so the user can never lose unresolved work behind the archive curtain.
    // resolve_actions must keep the action set in sync — otherwise the user
    // sees the thread in Review with dots but has no buttons to resolve it.
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Waiting,
        ArchiveState::Archived,
        true,
    );
    assert_eq!(actions, vec![Action::Discard, Action::Apply]);
}

// ── ChangeProposed must surface CC threads in REVIEW ──

#[test]
fn change_proposed_surfaces_cc_to_inbox() {
    // Bug: ChangeProposed was in the no_change bucket, so CC threads with
    // proposed changes went to HISTORY instead of REVIEW when there was no
    // prior CodingAgentIdled (or user had already read the thread).
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section,
        Some(ArchiveState::Inbox),
        "ChangeProposed must surface CC thread to inbox so the Apply panel appears"
    );
}

#[test]
fn change_proposed_keeps_cc_in_inbox_if_already_in_inbox() {
    let result = resolve_transition(
        "ChangeProposed",
        ThreadType::CodingAgent,
        ArchiveState::Inbox,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));
}

#[test]
fn cc_running_shows_no_actions() {
    let actions = resolve_actions(
        ThreadType::CodingAgent,
        ThreadStatus::Running,
        ArchiveState::Inbox,
        true,
    );
    assert!(actions.is_empty());
}

// ── UserQuestionAsked / UserQuestionAnswered tests ──

#[test]
fn user_question_asked_surfaces_cc_to_inbox() {
    let result = resolve_transition(
        "UserQuestionAsked",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    )
    .unwrap();
    assert_eq!(result.new_section, Some(ArchiveState::Inbox));}

#[test]
fn user_question_asked_rejected_for_chat() {
    let result = resolve_transition(
        "UserQuestionAsked",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    );
    assert!(result.is_err(), "UserQuestionAsked must be CC-only");
}

#[test]
fn user_question_answered_no_section_change() {
    let result = resolve_transition(
        "UserQuestionAnswered",
        ThreadType::CodingAgent,
        ArchiveState::Inbox,
        true,
    )
    .unwrap();
    assert_eq!(
        result.new_section, None,
        "answer event keeps thread in REVIEW until next terminal"
    );
}

#[test]
fn user_question_asked_classified_action_required() {
    assert_eq!(
        classify_event("UserQuestionAsked"),
        Some(EventClass::ActionRequired)
    );
}

#[test]
fn user_question_asked_status_transition() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    let t = transitions
        .get("UserQuestionAsked")
        .expect("status transition");
    assert_eq!(
        t.status,
        StatusRule::Set(ThreadStatus::WaitingForUserAnswer)
    );
    assert_eq!(t.cc_flags, CcFlagRule::None);
}

#[test]
fn user_question_answered_status_transition_resumes_running() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    let t = transitions
        .get("UserQuestionAnswered")
        .expect("status transition");
    assert_eq!(t.status, StatusRule::Set(ThreadStatus::Running));
}

#[test]
fn waiting_for_user_answer_routes_to_review_when_inbox() {
    // The transition contract guarantees `UserQuestionAsked` stamps
    // archive_state = Inbox, so the typical WFUA thread routes to Review.
    assert_eq!(
        display_section(
            ArchiveState::Inbox,
            ThreadStatus::WaitingForUserAnswer,
            false,
            false,
            false
        ),
        DisplaySection::Review
    );
    // An archived legacy WFUA row routes to Archive (no special case anymore).
    // The transition contract enforces Inbox so this state shouldn't occur
    // in practice; the assertion documents the new behavior.
    assert_eq!(
        display_section(
            ArchiveState::Archived,
            ThreadStatus::WaitingForUserAnswer,
            false,
            false,
            false
        ),
        DisplaySection::Archive
    );
    // Saved beats WFUA — the saved-section badge surfaces the question.
    assert_eq!(
        display_section(
            ArchiveState::Inbox,
            ThreadStatus::WaitingForUserAnswer,
            true,
            false,
            false
        ),
        DisplaySection::Saved
    );
    // Active children turn it Active (which already reads as work-in-progress).
    assert_eq!(
        display_section(
            ArchiveState::Inbox,
            ThreadStatus::WaitingForUserAnswer,
            false,
            true,
            false
        ),
        DisplaySection::Active
    );
}

#[test]
fn waiting_for_user_answer_returns_no_actions() {
    // Mid-turn: Apply/Discard must never appear (incomplete work) and Archive
    // is replaced by a separately-rendered Cancel.
    for section in [ArchiveState::Inbox, ArchiveState::Archived] {
        for has_changes in [true, false] {
            let actions = resolve_actions(
                ThreadType::CodingAgent,
                ThreadStatus::WaitingForUserAnswer,
                section,
                has_changes,
            );
            assert!(
                actions.is_empty(),
                "WaitingForUserAnswer must yield no actions (section={:?}, has_changes={}); Cancel is rendered separately",
                section,
                has_changes,
            );
        }
    }
}

#[test]
fn user_question_events_are_persisted() {
    assert!(all_persisted_event_types().contains(&"UserQuestionAsked"));
    assert!(all_persisted_event_types().contains(&"UserQuestionAnswered"));
}

// CodingAgentSettingsChanged must be accepted for CC threads (persisted metadata, no section change)
#[test]
fn cc_settings_changed_accepted_for_cc_threads() {
    let result = resolve_transition(
        "CodingAgentSettingsChanged",
        ThreadType::CodingAgent,
        ArchiveState::Archived,
        true,
    );
    assert!(
        result.is_ok(),
        "CodingAgentSettingsChanged must be accepted for CC threads"
    );
    let result = result.unwrap();
    assert_eq!(
        result.new_section, None,
        "CodingAgentSettingsChanged must not change section"
    );}

#[test]
fn cc_settings_changed_rejected_for_chat_threads() {
    let result = resolve_transition(
        "CodingAgentSettingsChanged",
        ThreadType::Chat,
        ArchiveState::Archived,
        true,
    );
    assert!(
        result.is_err(),
        "CodingAgentSettingsChanged must be rejected for Chat threads"
    );
}

#[test]
fn cc_settings_changed_is_classified() {
    assert!(
        classify_event("CodingAgentSettingsChanged").is_some(),
        "CodingAgentSettingsChanged must be classified"
    );
}

#[test]
fn cc_settings_changed_is_persisted_event() {
    assert!(
        all_persisted_event_types().contains(&"CodingAgentSettingsChanged"),
        "CodingAgentSettingsChanged must be in all_persisted_event_types()"
    );
}

// 22b. last_activity_events_are_valid_persisted_events
#[test]
fn last_activity_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for event in LAST_ACTIVITY_EVENTS {
        assert!(
            all.contains(event),
            "LAST_ACTIVITY_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// Events that update last_activity in the backend projection (event_bus.rs)
// must be in LAST_ACTIVITY_EVENTS so the frontend drawer timestamp stays in sync.
#[test]
fn required_events_are_in_last_activity() {
    for event in &[
        "ToolCalled",
        "ToolResult",
        "TextStreamed",
        "Thinking",
        "CodingAgentTextStreamed",
        "CodingAgentToolCalled",
        "CodingAgentToolResult",
        "TriggerCompleted",
    ] {
        assert!(
            LAST_ACTIVITY_EVENTS.contains(event),
            "'{}' must be in LAST_ACTIVITY_EVENTS — it updates last_activity in \
                 event_bus.rs but the frontend won't sync without it",
            event
        );
    }
}

#[test]
fn status_transition_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in status_transitions() {
        assert!(
            all.contains(&event),
            "status_transitions contains '{}' which is not a persisted event type",
            event
        );
    }
}

#[test]
fn message_count_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for event in MESSAGE_COUNT_EVENTS {
        assert!(
            all.contains(event),
            "MESSAGE_COUNT_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// 22c. cross_validation_fixture_is_up_to_date
#[test]
fn cross_validation_fixture_is_up_to_date() {
    let generated = generate_cross_validation_fixture();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lucidos-app/src/generated/cross-validation-fixture.json");
    if let Ok(existing) = std::fs::read_to_string(&path) {
        assert_eq!(
                existing, generated,
                "Cross-validation fixture is stale. Run: cargo test -p lucidos-engine generate_cross_validation_fixture_file -- --ignored"
            );
    } else {
        panic!(
                "Cross-validation fixture does not exist at {}. Run: cargo test -p lucidos-engine generate_cross_validation_fixture_file -- --ignored",
                path.display()
            );
    }
}

// 23. generated_typescript_is_up_to_date
#[test]
fn generated_typescript_is_up_to_date() {
    let generated = generate_typescript();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lucidos-app/src/generated/thread-lifecycle.ts");
    if let Ok(existing) = std::fs::read_to_string(&path) {
        assert_eq!(
                existing, generated,
                "Generated TypeScript is stale. Run: cargo test -p lucidos-engine generate_typescript_file -- --ignored"
            );
    } else {
        panic!(
                "Generated file does not exist at {}. Run: cargo test -p lucidos-engine generate_typescript_file -- --ignored",
                path.display()
            );
    }
}

// 24. generate_typescript_file (run explicitly to regenerate)
#[test]
#[ignore]
fn generate_typescript_file() {
    let generated = generate_typescript();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lucidos-app/src/generated/thread-lifecycle.ts");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, &generated).unwrap();
    crate::log!("[ContractTest] Generated: {}", path.display());
}

// 24b. generate_cross_validation_fixture_file (run explicitly to regenerate)
#[test]
#[ignore]
fn generate_cross_validation_fixture_file() {
    let generated = generate_cross_validation_fixture();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lucidos-app/src/generated/cross-validation-fixture.json");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, &generated).unwrap();
    crate::log!("[ContractTest] Generated: {}", path.display());
}

// 25. start_events_set_status_running
#[test]
fn start_events_with_transitions_set_running() {
    // Start classification is about exchange grouping (UI), not status.
    // Some Start events (MissingHardeningDetected, MergeConflictDetected) don't
    // set status=running in event_bus.rs. This test only checks that Start events
    // that DO have a status transition always set Running (never idle/waiting).
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for event_type in all_persisted_event_types() {
        if classify_event(event_type) == Some(EventClass::Start) {
            if let Some(t) = transitions.get(event_type) {
                if let StatusRule::Set(s) = &t.status {
                    assert_eq!(
                        *s,
                        ThreadStatus::Running,
                        "Start event '{}' with Set status should set Running, not {:?}",
                        event_type,
                        s
                    );
                }
            }
        }
    }
}

// 26. terminal_events_never_set_running
#[test]
fn terminal_events_never_set_running() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for event_type in all_persisted_event_types() {
        if classify_event(event_type) == Some(EventClass::Terminal) {
            if let Some(t) = transitions.get(event_type) {
                match &t.status {
                    StatusRule::Set(s) => assert_ne!(
                        *s,
                        ThreadStatus::Running,
                        "Terminal event '{}' should not set Running",
                        event_type
                    ),
                    StatusRule::ConditionalCc(w, wo) => {
                        assert_ne!(
                            *w,
                            ThreadStatus::Running,
                            "Terminal '{}' withChanges should not be Running",
                            event_type
                        );
                        assert_ne!(
                            *wo,
                            ThreadStatus::Running,
                            "Terminal '{}' withoutChanges should not be Running",
                            event_type
                        );
                    }
                    StatusRule::NoChange => {}
                }
            }
        }
    }
}

// 27. section_transition_events_are_valid_persisted_events
#[test]
fn section_transition_events_are_valid_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in SECTION_TRANSITION_EVENTS {
        assert!(
            all.contains(event),
            "SECTION_TRANSITION_EVENTS contains '{}' which is not a persisted event type",
            event
        );
    }
}

// ── Phase 0: Pre-refactor safety net ──

/// Cross-validate: events with status_transitions Setting → Running must be
/// classified as Start (or at least not Terminal). Events Setting → Idle/Waiting
/// must NOT be classified as Start.
#[test]
fn status_transition_classification_consistency() {
    let transitions: std::collections::HashMap<&str, StatusTransition> =
        status_transitions().into_iter().collect();
    for (event, transition) in &transitions {
        let class = classify_event(event);
        match &transition.status {
            StatusRule::Set(ThreadStatus::Running) => {
                // Running-setters should be Start or Activity, never Terminal
                if let Some(c) = class {
                    assert_ne!(
                        c,
                        EventClass::Terminal,
                        "Event '{}' sets Running but is classified as Terminal",
                        event
                    );
                }
            }
            StatusRule::Set(ThreadStatus::Idle)
            | StatusRule::Set(ThreadStatus::Waiting)
            | StatusRule::Set(ThreadStatus::Failed) => {
                // Idle/Waiting/Failed-setters should NOT be Start
                if let Some(c) = class {
                    assert_ne!(
                        c,
                        EventClass::Start,
                        "Event '{}' sets non-running terminal status but is classified as Start",
                        event
                    );
                }
            }
            _ => {} // ConditionalCc and NoChange are fine in any class
        }
    }
}

/// Cross-validate: CcFlagRule != None should only appear on CC-relevant events
/// (Change*, ClaudeCode*, MergeConflict*, ThreadArchived). This catches accidental
/// cc_has_changes/cc_applying mutations on chat-only events.
#[test]
fn cc_flag_rules_only_on_cc_relevant_events() {
    let cc_relevant_prefixes = ["Change", "CodingAgent", "MergeConflict", "ThreadArchived"];
    for (event, transition) in status_transitions() {
        if transition.cc_flags != CcFlagRule::None {
            let is_cc_relevant = cc_relevant_prefixes
                .iter()
                .any(|prefix| event.starts_with(prefix));
            assert!(
                is_cc_relevant,
                "Event '{}' has CcFlagRule {:?} but doesn't match any CC-relevant prefix {:?}",
                event, transition.cc_flags, cc_relevant_prefixes
            );
        }
    }
}

/// Cross-validate: MESSAGE_COUNT_EVENTS should all be Start events —
/// only user-initiated "start of exchange" events increment the count.
#[test]
fn message_count_events_are_start_events() {
    for event in MESSAGE_COUNT_EVENTS {
        let class = classify_event(event);
        assert_eq!(
                class,
                Some(EventClass::Start),
                "MESSAGE_COUNT_EVENT '{}' should be classified as Start (it starts a new exchange), got {:?}",
                event, class
            );
    }
}

/// Cross-validate: every event that has a StatusTransition must be a persisted
/// event type. Transient events should never appear in status_transitions().
#[test]
fn status_transitions_only_contain_persisted_events() {
    let all = all_persisted_event_types();
    for (event, _) in status_transitions() {
        assert!(
            all.contains(&event),
            "status_transitions() contains '{}' which is not in all_persisted_event_types(). \
                 Transient events must not have status transitions.",
            event
        );
    }
}

/// Cross-validate: Start events that set status=Running should also appear in
/// LAST_ACTIVITY_EVENTS (they start a new exchange, so they're activity).
/// Activity-classified events (like CodingAgentPromptSent) may set Running
/// without updating last_activity — they only update last_revived_at.
#[test]
fn start_running_setters_are_in_last_activity_events() {
    for (event, transition) in status_transitions() {
        if let StatusRule::Set(ThreadStatus::Running) = transition.status {
            if classify_event(event) == Some(EventClass::Start) {
                assert!(
                    LAST_ACTIVITY_EVENTS.contains(&event),
                    "Start event '{}' sets status=Running but is NOT in LAST_ACTIVITY_EVENTS. \
                         Start events begin new exchanges and should update last_activity.",
                    event
                );
            }
        }
    }
}
