use chrono::{DateTime, Utc};
use serde::Serialize;
use uuid::Uuid;

/// A tool execution step (for history display)
#[derive(Clone, Debug, Serialize)]
pub struct Step {
    pub description: String,
    pub tool_name: Option<String>,
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_tokens: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_messages: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trimmed: Option<bool>,
}

/// A response event — either a text block (raw markdown) or a step.
/// Serialized as a tagged enum with `"type": "text"` or `"type": "step"`.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type")]
pub enum ResponseEvent {
    #[serde(rename = "text")]
    Text { md: String },
    #[serde(rename = "step")]
    Step {
        description: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        tool_name: Option<String>,
        success: bool,
        #[serde(skip_serializing_if = "Option::is_none")]
        detail: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        context_tokens: Option<usize>,
        #[serde(skip_serializing_if = "Option::is_none")]
        context_messages: Option<usize>,
        #[serde(skip_serializing_if = "Option::is_none")]
        trimmed: Option<bool>,
    },
    #[serde(rename = "section_break")]
    SectionBreak { channel: String },
}

/// A message in a session (for history time travel)
#[derive(Clone, Debug, Serialize)]
pub struct SessionMessage {
    pub role: String,
    pub content: String,
    pub created_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub steps: Vec<Step>,
    #[serde(skip)]
    pub images: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub user_images: Vec<UserImagePayload>,
    /// Brief text description of attached images (generated by Flash on send).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_description: Option<String>,
    /// Response completion status:
    /// - `Some(true)`: completed normally (ResponseGenerated event)
    /// - `Some(false)`: interrupted — a follow-up user message arrived mid-stream
    /// - `None`: unknown/still in progress (trailing buffer flush, no definitive outcome)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    /// True if this response was canceled by the user (ResponseCanceled event).
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub canceled: bool,
    /// True if this response was aborted by the system (ResponseAborted event).
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub aborted: bool,
    /// Individual text chunks from streaming, split at tool call boundaries.
    /// Each chunk is the accumulated text buffer content at the time a tool was called.
    /// Used by the frontend "Show details" toggle to reveal intermediate text.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub text_chunks: Vec<String>,
    /// Ordered response events: interleaved text blocks (raw markdown) and steps.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub events: Vec<ResponseEvent>,
    /// UUID of the request (MessageReceived or TriggerStarted) that triggered this response.
    /// Present on assistant messages, used for explicit linkage instead of positional grouping.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_event_id: Option<String>,
    /// This event's own UUID (from the Event.id field).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_id: Option<String>,
    /// Thread this message belongs to (from event payload's thread_id field).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

/// A user-attached image (base64 + mime type) stored in MessageReceived event payloads.
#[derive(Clone, Debug, Serialize)]
pub struct UserImagePayload {
    pub base64: String,
    pub mime_type: String,
}

/// A message in a conversation snapshot (for time-travel view)
#[derive(Clone, Debug, Serialize)]
pub struct ConversationMessage {
    pub role: String,
    pub content: String,
    pub event_id: Uuid,
    pub timestamp: DateTime<Utc>,
    pub steps: Vec<Step>,
    pub images: Vec<String>,
}

/// A snapshot of the conversation at a specific point in time
#[derive(Clone, Debug, Serialize)]
pub struct ConversationSnapshot {
    pub at_event_id: Uuid,
    pub point_in_time: DateTime<Utc>,
    pub messages: Vec<ConversationMessage>,
    pub artifacts: Vec<String>,
    pub git_commit: Option<String>,
}
