//! Content-addressed blob store for user-attached images.
//!
//! Bytes live exactly once on disk under
//! `<workspace>/data/blobs/<hh>/<hash>.<ext>` where `<hash>` is the hex
//! sha256 and `<hh>` is the first two hex chars (256-way fan-out).
//!
//! Same bytes uploaded twice = the second call is a no-op on disk.
//! Mime is sniffed server-side from magic bytes against an image-only
//! allowlist; the canonical file extension is derived from the sniffed
//! mime, not from any user-supplied filename.

use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

const BLOBS_SUBDIR: &str = "data/blobs";

/// Cache for downscaled preview JPEGs. Lives under `.lucidos/` (gitignored,
/// rebuildable) — derived from the originals, can always be regenerated by
/// re-running `get_or_create_preview`.
const PREVIEWS_SUBDIR: &str = ".lucidos/blob-previews";

/// Long-edge cap for browser-facing previews. iOS Safari/WebKit silently
/// fails to render images whose decoded bitmap exceeds its per-image
/// memory budget — the symptom is an `<img>` element that loads and then
/// renders fully black. 2048 px keeps the decoded RGBA bitmap at ~16 MB
/// (well inside WebKit's budget on iPhone) while still giving comfortable
/// headroom for the popup viewer's pinch-zoom.
pub const PREVIEW_MAX_EDGE: u32 = 2048;

const PREVIEW_MIME: &str = "image/jpeg";
const PREVIEW_EXT: &str = "jpg";
const PREVIEW_JPEG_QUALITY: u8 = 85;

/// Single source of truth for the image allowlist: (mime, canonical
/// extension). `sniff_image_mime` returns one of these mime strings;
/// `ext_for_mime` and `resolve_blob` look up the paired extension.
/// Add a new image format by appending one entry here AND extending the
/// magic-byte sniff in `sniff_image_mime`.
const ALLOWED_IMAGE_MIME_EXT: &[(&str, &str)] = &[
    ("image/png", "png"),
    ("image/jpeg", "jpg"),
    ("image/webp", "webp"),
    ("image/gif", "gif"),
    ("image/heic", "heic"),
];

#[derive(Debug)]
pub enum BlobError {
    UnsupportedMime,
    BadEncoding(String),
    Io(std::io::Error),
}

impl std::fmt::Display for BlobError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BlobError::UnsupportedMime => write!(
                f,
                "unsupported image mime (allowed: jpeg, png, webp, gif, heic)"
            ),
            BlobError::BadEncoding(detail) => write!(f, "invalid base64 in image: {detail}"),
            BlobError::Io(e) => write!(f, "blob io error: {e}"),
        }
    }
}

impl std::error::Error for BlobError {}

impl From<std::io::Error> for BlobError {
    fn from(e: std::io::Error) -> Self {
        BlobError::Io(e)
    }
}

/// A blob's content-addressed identity plus metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedBlob {
    /// sha256(bytes) as lowercase hex (64 chars).
    pub hash: String,
    /// Sniffed mime from the allowlist.
    pub mime: String,
    /// Raw byte size (not base64-inflated).
    pub byte_size: u64,
    /// Absolute path to the blob on disk.
    pub path: PathBuf,
}

/// Compute lowercase hex sha256 of `bytes`.
pub fn compute_hash(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    digest.iter().fold(String::with_capacity(64), |mut acc, b| {
        use std::fmt::Write as _;
        let _ = write!(acc, "{:02x}", b);
        acc
    })
}

/// Sniff a recognized image mime from magic bytes. Returns `None` for
/// anything outside the image allowlist (jpeg, png, webp, gif, heic).
///
/// HEIC detection requires looking past the leading box-size bytes to
/// the `ftyp` box brand at offset 4–11; the rest are leading-byte checks.
pub fn sniff_image_mime(bytes: &[u8]) -> Option<&'static str> {
    if bytes.len() >= 8 && bytes[..8] == [0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A] {
        return Some("image/png");
    }
    if bytes.len() >= 3 && bytes[..3] == [0xFF, 0xD8, 0xFF] {
        return Some("image/jpeg");
    }
    if bytes.len() >= 12 && &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WEBP" {
        return Some("image/webp");
    }
    if bytes.len() >= 6 && (&bytes[..6] == b"GIF87a" || &bytes[..6] == b"GIF89a") {
        return Some("image/gif");
    }
    // HEIC family — bytes 4..8 are `ftyp`, bytes 8..12 are the brand.
    // Allowed brands: heic, heix, hevc, hevx, mif1, msf1 (Apple's
    // multi-image HEIF variants that PHPicker can hand us).
    if bytes.len() >= 12 && &bytes[4..8] == b"ftyp" {
        let brand = &bytes[8..12];
        if matches!(
            brand,
            b"heic" | b"heix" | b"hevc" | b"hevx" | b"mif1" | b"msf1"
        ) {
            return Some("image/heic");
        }
    }
    None
}

/// Canonical filename extension for a recognized mime. Pairs with
/// `sniff_image_mime` — the same set of types is supported.
pub fn ext_for_mime(mime: &str) -> Option<&'static str> {
    ALLOWED_IMAGE_MIME_EXT
        .iter()
        .find_map(|(m, ext)| (*m == mime).then_some(*ext))
}

/// Build the on-disk path for a blob with `hash` and `ext`.
fn blob_path(workspace: &Path, hash: &str, ext: &str) -> PathBuf {
    workspace
        .join(BLOBS_SUBDIR)
        .join(&hash[..2])
        .join(format!("{hash}.{ext}"))
}

/// Write `bytes` to the content-addressed location under
/// `<workspace>/data/blobs/`. Idempotent — if the file already exists at
/// the canonical path, it is left untouched (content-addressed, so the
/// existing bytes are by construction identical).
///
/// Returns `BlobError::UnsupportedMime` for bytes outside the image
/// allowlist (so the upload endpoint can reject with 415 before any
/// disk write).
///
/// The write goes to a sibling `.tmp-<hash>` path then renames into
/// place atomically; a crash mid-write leaves no half-written blob.
pub fn write_blob(workspace: &Path, bytes: &[u8]) -> Result<ResolvedBlob, BlobError> {
    let mime = sniff_image_mime(bytes).ok_or(BlobError::UnsupportedMime)?;
    let ext = ext_for_mime(mime).ok_or(BlobError::UnsupportedMime)?;
    let hash = compute_hash(bytes);
    let path = blob_path(workspace, &hash, ext);

    if !path.exists() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let tmp = path.with_file_name(format!(".tmp-{hash}.{ext}"));
        std::fs::write(&tmp, bytes)?;
        std::fs::rename(&tmp, &path)?;
    }

    Ok(ResolvedBlob {
        hash,
        mime: mime.to_string(),
        byte_size: bytes.len() as u64,
        path,
    })
}

/// Resolve an existing hash to its on-disk path + mime. Returns `None`
/// when no blob with that hash exists in any of the allowlisted-extension
/// fan-out slots — callers treat that as 404.
pub fn resolve_blob(workspace: &Path, hash: &str) -> Option<ResolvedBlob> {
    if hash.len() != 64 || !hash.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    for &(mime, ext) in ALLOWED_IMAGE_MIME_EXT {
        let path = blob_path(workspace, hash, ext);
        if let Ok(meta) = std::fs::metadata(&path) {
            return Some(ResolvedBlob {
                hash: hash.to_string(),
                mime: mime.to_string(),
                byte_size: meta.len(),
                path,
            });
        }
    }
    None
}

/// Resolve `hash` and read its bytes into a base64-encoded string + mime —
/// the shape every LLM-call constructor and `walk_thread_images` user
/// branch needs. Returns `None` when the blob is missing or unreadable;
/// callers either skip silently (LLM call) or log + skip (image walks).
pub fn read_blob_as_base64(workspace: &Path, hash: &str) -> Option<(String, String)> {
    use base64::Engine as _;
    let ResolvedBlob { mime, path, .. } = resolve_blob(workspace, hash)?;
    let bytes = std::fs::read(&path).ok()?;
    Some((
        base64::engine::general_purpose::STANDARD.encode(&bytes),
        mime,
    ))
}

/// JPEG files from phone cameras store pixels in the sensor's native
/// orientation (usually landscape) and use an EXIF tag to indicate how
/// to rotate for correct display. Browsers handle this automatically
/// when consuming the original bytes, but `image::load_from_memory()`
/// ignores EXIF — so any path that decodes + re-encodes (LLM-bound
/// compression, browser-facing preview) must rotate the pixels itself
/// or the re-encoded image will be sideways.
pub fn apply_exif_orientation(raw: &[u8], img: image::DynamicImage) -> image::DynamicImage {
    let mut cursor = std::io::Cursor::new(raw);
    let exif = match exif::Reader::new().read_from_container(&mut cursor) {
        Ok(exif) => exif,
        Err(_) => return img,
    };

    let orientation = match exif.get_field(exif::Tag::Orientation, exif::In::PRIMARY) {
        Some(field) => match field.value.get_uint(0) {
            Some(v) => v,
            None => return img,
        },
        None => return img,
    };

    match orientation {
        1 => img,
        2 => img.fliph(),
        3 => img.rotate180(),
        4 => img.flipv(),
        5 => img.rotate90().fliph(),
        6 => img.rotate90(),
        7 => img.rotate270().fliph(),
        8 => img.rotate270(),
        _ => img,
    }
}

fn preview_cache_path(workspace: &Path, hash: &str, max_edge: u32) -> PathBuf {
    workspace
        .join(PREVIEWS_SUBDIR)
        .join(&hash[..2])
        .join(format!("{hash}-{max_edge}.{PREVIEW_EXT}"))
}

fn preview_blob(path: PathBuf, hash: &str, byte_size: u64) -> ResolvedBlob {
    ResolvedBlob {
        hash: hash.to_string(),
        mime: PREVIEW_MIME.to_string(),
        byte_size,
        path,
    }
}

/// Resolve `hash` and return a `<= max_edge px on long edge` JPEG suitable
/// for browser display. Caches the resized result under `.lucidos/` so the
/// second request is a plain disk read.
///
/// Returns:
///   - `Ok(None)` — no blob with that hash on disk (caller serves 404).
///   - `Ok(Some(blob))` — the original (when small enough or undecodable)
///     or the cached preview (when downscaling happened).
///   - `Err(_)` — only filesystem errors; decode failures fall back to
///     the original since iOS Safari renders most browser-supported
///     formats natively at small sizes.
///
/// Concurrent requests for the same uncached hash will each decode + write
/// independently. The atomic `tmp → rename` keeps the cache file consistent;
/// the duplicate CPU is accepted (one user-visible cache miss per blob in
/// practice — subsequent loads hit the cache).
pub fn get_or_create_preview(
    workspace: &Path,
    hash: &str,
    max_edge: u32,
) -> Result<Option<ResolvedBlob>, BlobError> {
    let original = match resolve_blob(workspace, hash) {
        Some(r) => r,
        None => return Ok(None),
    };

    let cache_path = preview_cache_path(workspace, hash, max_edge);
    if let Ok(meta) = std::fs::metadata(&cache_path) {
        return Ok(Some(preview_blob(cache_path, hash, meta.len())));
    }

    let original_bytes = std::fs::read(&original.path)?;
    let img = match image::load_from_memory(&original_bytes) {
        Ok(i) => i,
        Err(_) => return Ok(Some(original)),
    };
    let img = apply_exif_orientation(&original_bytes, img);

    if img.width().max(img.height()) <= max_edge {
        return Ok(Some(original));
    }

    let rgb = img
        .resize(max_edge, max_edge, image::imageops::FilterType::Lanczos3)
        .to_rgb8();

    let mut buf: Vec<u8> = Vec::new();
    {
        use image::codecs::jpeg::JpegEncoder;
        use image::{ColorType, ImageEncoder};
        JpegEncoder::new_with_quality(&mut buf, PREVIEW_JPEG_QUALITY)
            .write_image(
                rgb.as_raw(),
                rgb.width(),
                rgb.height(),
                ColorType::Rgb8.into(),
            )
            .map_err(|e| BlobError::Io(std::io::Error::other(e)))?;
    }

    if let Some(parent) = cache_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // Per-call nonce in the tmp filename so two concurrent requests for the
    // same uncached hash don't share a tmp path — without it, the first to
    // rename takes the file out from under the second, whose own rename
    // then fails with ENOENT and surfaces as 500.
    let nonce = uuid::Uuid::new_v4().simple();
    let tmp = cache_path.with_file_name(format!(".tmp-{hash}-{max_edge}-{nonce}.{PREVIEW_EXT}"));
    std::fs::write(&tmp, &buf)?;
    std::fs::rename(&tmp, &cache_path)?;

    Ok(Some(preview_blob(cache_path, hash, buf.len() as u64)))
}

/// Decode `base64_str`, sniff its mime, and write it into the blob store.
/// Same idempotency guarantees as `write_blob`. Used by HTTP compat shims
/// (legacy `[{base64, mime_type}]` bodies) and by the chat send path that
/// hashes inline `ChatImage` payloads at MessageReceived emit time.
pub fn write_blob_from_base64(
    workspace: &Path,
    base64_str: &str,
) -> Result<ResolvedBlob, BlobError> {
    use base64::Engine as _;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_str)
        .map_err(|e| BlobError::BadEncoding(e.to_string()))?;
    write_blob(workspace, &bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal valid PNG (1×1 transparent) — just enough to satisfy the
    /// magic-byte sniff. Body is the smallest PNG that browsers/Anthropic
    /// consistently accept; any truncation past the header is fine for
    /// these tests since we only sniff the leading bytes.
    fn png_bytes() -> Vec<u8> {
        vec![
            0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A, // signature
            0x00, 0x00, 0x00, 0x0D, b'I', b'H', b'D', b'R', // IHDR start
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00,
        ]
    }

    fn jpeg_bytes() -> Vec<u8> {
        vec![0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, b'J', b'F', b'I', b'F']
    }

    fn webp_bytes() -> Vec<u8> {
        let mut v = b"RIFF\x24\x00\x00\x00WEBPVP8 ".to_vec();
        v.extend_from_slice(&[0x00; 16]);
        v
    }

    fn gif_bytes() -> Vec<u8> {
        b"GIF89a".to_vec()
    }

    fn heic_bytes() -> Vec<u8> {
        // 4-byte box size, then "ftyp", then "heic" brand.
        let mut v = vec![0x00, 0x00, 0x00, 0x18];
        v.extend_from_slice(b"ftyp");
        v.extend_from_slice(b"heic");
        v.extend_from_slice(&[0x00; 12]);
        v
    }

    #[test]
    fn compute_hash_returns_lowercase_hex_sha256_for_known_input() {
        // sha256("hello") = 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
        assert_eq!(
            compute_hash(b"hello"),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }

    #[test]
    fn compute_hash_returns_64_hex_chars_for_arbitrary_input() {
        let h = compute_hash(b"any random bytes here");
        assert_eq!(h.len(), 64);
        assert!(h
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
    }

    #[test]
    fn sniff_image_mime_recognizes_png() {
        assert_eq!(sniff_image_mime(&png_bytes()), Some("image/png"));
    }

    #[test]
    fn sniff_image_mime_recognizes_jpeg() {
        assert_eq!(sniff_image_mime(&jpeg_bytes()), Some("image/jpeg"));
    }

    #[test]
    fn sniff_image_mime_recognizes_webp() {
        assert_eq!(sniff_image_mime(&webp_bytes()), Some("image/webp"));
    }

    #[test]
    fn sniff_image_mime_recognizes_gif() {
        assert_eq!(sniff_image_mime(&gif_bytes()), Some("image/gif"));
    }

    #[test]
    fn sniff_image_mime_recognizes_heic_brand() {
        assert_eq!(sniff_image_mime(&heic_bytes()), Some("image/heic"));
    }

    /// HEIC's brand byte slot is sniff-tight on purpose — `ftyp` alone
    /// matches MP4/MOV/etc., which are NOT in the allowlist.
    #[test]
    fn sniff_image_mime_rejects_ftyp_without_heic_brand() {
        let mut v = vec![0x00, 0x00, 0x00, 0x18];
        v.extend_from_slice(b"ftypmp42"); // MP4 brand, not HEIC
        v.extend_from_slice(&[0x00; 12]);
        assert_eq!(sniff_image_mime(&v), None);
    }

    #[test]
    fn sniff_image_mime_rejects_text() {
        assert_eq!(sniff_image_mime(b"this is not an image"), None);
    }

    #[test]
    fn sniff_image_mime_rejects_too_short() {
        assert_eq!(sniff_image_mime(b""), None);
        assert_eq!(sniff_image_mime(&[0x89, 0x50]), None);
    }

    #[test]
    fn ext_for_mime_returns_jpg_for_jpeg() {
        // Important: NOT "jpeg" — match the convention iOS / Anthropic use.
        assert_eq!(ext_for_mime("image/jpeg"), Some("jpg"));
    }

    #[test]
    fn ext_for_mime_returns_none_for_unknown() {
        assert_eq!(ext_for_mime("application/pdf"), None);
    }

    #[test]
    fn write_blob_writes_at_fan_out_path_and_returns_resolved() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = png_bytes();
        let resolved = write_blob(dir.path(), &bytes).expect("write_blob");

        let expected_hash = compute_hash(&bytes);
        assert_eq!(resolved.hash, expected_hash);
        assert_eq!(resolved.mime, "image/png");
        assert_eq!(resolved.byte_size, bytes.len() as u64);

        let expected_path = dir
            .path()
            .join("data/blobs")
            .join(&expected_hash[..2])
            .join(format!("{expected_hash}.png"));
        assert_eq!(resolved.path, expected_path);
        assert!(expected_path.exists(), "blob file must exist on disk");
        let on_disk = std::fs::read(&expected_path).unwrap();
        assert_eq!(on_disk, bytes, "on-disk bytes must equal input");
    }

    #[test]
    fn write_blob_is_idempotent_on_repeat() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = png_bytes();
        let first = write_blob(dir.path(), &bytes).unwrap();
        let second = write_blob(dir.path(), &bytes).unwrap();
        assert_eq!(first, second, "second write returns identical Resolved");
        assert!(first.path.exists());
        // No leftover .tmp file from the second call.
        let parent = first.path.parent().unwrap();
        let entries: Vec<_> = std::fs::read_dir(parent)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().into_string().unwrap())
            .collect();
        assert!(
            !entries.iter().any(|n| n.starts_with(".tmp-")),
            "no .tmp-* files after idempotent write: {entries:?}"
        );
    }

    #[test]
    fn write_blob_rejects_non_image_bytes_with_unsupported_mime() {
        let dir = tempfile::tempdir().unwrap();
        let result = write_blob(dir.path(), b"plain text not an image");
        assert!(matches!(result, Err(BlobError::UnsupportedMime)));
        // Guarantee no disk write happened.
        assert!(
            !dir.path().join("data/blobs").exists(),
            "rejected upload must not create the blobs directory"
        );
    }

    #[test]
    fn resolve_blob_round_trips_after_write() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = png_bytes();
        let written = write_blob(dir.path(), &bytes).unwrap();
        let resolved = resolve_blob(dir.path(), &written.hash).expect("resolve after write");
        assert_eq!(resolved, written);
    }

    #[test]
    fn resolve_blob_returns_none_for_unknown_hash() {
        let dir = tempfile::tempdir().unwrap();
        assert!(resolve_blob(dir.path(), &"a".repeat(64)).is_none());
    }

    /// Defensive — a malformed hash (too short, non-hex) must not be
    /// passed to filesystem joins. Caller-level path-traversal guard.
    #[test]
    fn resolve_blob_returns_none_for_malformed_hash() {
        let dir = tempfile::tempdir().unwrap();
        assert!(resolve_blob(dir.path(), "short").is_none());
        assert!(resolve_blob(dir.path(), "..").is_none());
        // 64 chars but with non-hex
        assert!(resolve_blob(dir.path(), &"g".repeat(64)).is_none());
    }

    /// Encode a real JPEG of given size — needed to exercise the decode
    /// + downscale path in `get_or_create_preview`. Solid color, smallest
    ///   possible payload that still round-trips through the `image` crate.
    fn encoded_jpeg(width: u32, height: u32) -> Vec<u8> {
        use image::codecs::jpeg::JpegEncoder;
        use image::{ColorType, ImageEncoder};
        let pixels = vec![128u8; (width * height * 3) as usize];
        let mut buf: Vec<u8> = Vec::new();
        let encoder = JpegEncoder::new_with_quality(&mut buf, 70);
        encoder
            .write_image(&pixels, width, height, ColorType::Rgb8.into())
            .expect("encode jpeg");
        buf
    }

    #[test]
    fn get_or_create_preview_returns_original_when_image_within_max_edge() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = encoded_jpeg(800, 600);
        let written = write_blob(dir.path(), &bytes).unwrap();

        let preview = get_or_create_preview(dir.path(), &written.hash, 2048)
            .expect("Ok for known small image")
            .expect("Some for known small image");

        assert_eq!(preview.path, written.path, "small image: serve original");
        assert_eq!(preview.mime, written.mime);
        assert_eq!(preview.byte_size, written.byte_size);
    }

    #[test]
    fn get_or_create_preview_downscales_long_edge_to_max_when_image_exceeds_it() {
        let dir = tempfile::tempdir().unwrap();
        // 4000 long edge, 3000 short edge — caps at long edge, scales short
        // proportionally → expected 2048×1536.
        let bytes = encoded_jpeg(4000, 3000);
        let written = write_blob(dir.path(), &bytes).unwrap();

        let preview = get_or_create_preview(dir.path(), &written.hash, 2048)
            .expect("Ok for known large image")
            .expect("Some for known large image");

        assert_ne!(
            preview.path, written.path,
            "large image: distinct preview file"
        );
        assert_eq!(preview.mime, "image/jpeg", "preview is always JPEG");
        assert!(preview.path.exists(), "preview file must exist on disk");
        assert!(
            preview.byte_size < written.byte_size,
            "preview should be smaller than original ({} >= {})",
            preview.byte_size,
            written.byte_size
        );

        let preview_bytes = std::fs::read(&preview.path).unwrap();
        let img = image::load_from_memory(&preview_bytes).expect("decode preview jpeg");
        assert_eq!(
            (img.width(), img.height()),
            (2048, 1536),
            "long edge clamped, aspect preserved"
        );
    }

    #[test]
    fn get_or_create_preview_caches_result_on_disk_for_second_call() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = encoded_jpeg(4000, 3000);
        let written = write_blob(dir.path(), &bytes).unwrap();

        let first = get_or_create_preview(dir.path(), &written.hash, 2048)
            .unwrap()
            .unwrap();
        let mtime_first = std::fs::metadata(&first.path).unwrap().modified().unwrap();

        // Force a clock tick so we can detect a re-write — fs mtime
        // resolution is OS-dependent but always >= 1 ms in practice.
        std::thread::sleep(std::time::Duration::from_millis(20));

        let second = get_or_create_preview(dir.path(), &written.hash, 2048)
            .unwrap()
            .unwrap();
        let mtime_second = std::fs::metadata(&second.path).unwrap().modified().unwrap();

        assert_eq!(first.path, second.path);
        assert_eq!(
            mtime_first, mtime_second,
            "second call must serve from cache, not re-encode"
        );
    }

    #[test]
    fn get_or_create_preview_returns_none_for_unknown_hash() {
        let dir = tempfile::tempdir().unwrap();
        match get_or_create_preview(dir.path(), &"a".repeat(64), 2048) {
            Ok(None) => {}
            other => panic!("expected Ok(None) for unknown hash, got {other:?}"),
        }
    }

    /// HEIC bytes can't be decoded by the `image` crate (no built-in
    /// codec). Fall back to serving the original — iOS Safari renders
    /// HEIC natively, and HEIC files from iPhones are already small enough
    /// (~2 MB) to clear WebKit's per-image decode budget. Same fallback
    /// applies to any decode failure: prefer "original works" over
    /// "broken preview".
    #[test]
    fn get_or_create_preview_falls_back_to_original_when_decode_fails() {
        let dir = tempfile::tempdir().unwrap();
        let bytes = heic_bytes();
        let written = write_blob(dir.path(), &bytes).unwrap();

        let preview = get_or_create_preview(dir.path(), &written.hash, 2048)
            .expect("must not error on undecodable bytes")
            .expect("Some for an existing hash");

        assert_eq!(preview.path, written.path, "fallback: serve original bytes");
        assert_eq!(preview.mime, "image/heic");
    }
}
